-- =====================================================================
-- MuleWatch :: 01_tables.sql   (all table DDL)
-- =====================================================================
USE ROLE MULEWATCH_ADMIN;
USE DATABASE MULEWATCH;
USE WAREHOUSE MULEWATCH_WH;

-- ============================ RAW ====================================
CREATE OR REPLACE TABLE RAW.CUSTOMERS (
  CUSTOMER_ID VARCHAR PRIMARY KEY, FULL_NAME VARCHAR, DOB DATE, GENDER VARCHAR,
  PHONE VARCHAR, EMAIL VARCHAR, PAN VARCHAR, AADHAAR_LAST4 VARCHAR,
  CITY VARCHAR, STATE VARCHAR, REGION VARCHAR,
  OCCUPATION_DECLARED VARCHAR, ANNUAL_INCOME_DECLARED NUMBER(14,2),
  KYC_LEVEL VARCHAR, ONBOARD_DATE DATE, ONBOARD_CHANNEL VARCHAR,
  BRANCH_ID VARCHAR, CUSTOMER_SEGMENT VARCHAR
) COMMENT = 'Core banking customer master (synthetic)';

CREATE OR REPLACE TABLE RAW.ACCOUNTS (
  ACCOUNT_ID VARCHAR PRIMARY KEY, CUSTOMER_ID VARCHAR, ACCOUNT_TYPE VARCHAR,
  OPEN_DATE DATE, STATUS VARCHAR, BRANCH_ID VARCHAR, REGION VARCHAR, CITY VARCHAR,
  VPA VARCHAR, IFSC VARCHAR
) COMMENT = 'Deposit & wallet accounts (synthetic)';

CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
  TXN_ID VARCHAR PRIMARY KEY, TXN_TS TIMESTAMP_NTZ, CHANNEL VARCHAR,
  AMOUNT NUMBER(14,2), SRC_ACCOUNT_ID VARCHAR, DST_ACCOUNT_ID VARCHAR,
  COUNTERPARTY_VPA VARCHAR, REMARKS VARCHAR, STATUS VARCHAR,
  GEO_CITY VARCHAR, DEVICE_ID VARCHAR
) CLUSTER BY (TO_DATE(TXN_TS))
  COMMENT = 'UPI / IMPS / NEFT / cash / ATM ledger. External parties are prefixed EXT-, cash is CASH';

CREATE OR REPLACE TABLE RAW.DEVICE_EVENTS (
  EVENT VARIANT, INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Semi-structured mobile banking telemetry (JSON)';

CREATE OR REPLACE TABLE RAW.PAYMENT_MESSAGES (
  MSG VARIANT, RECEIVED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Semi-structured outward NEFT/IMPS payment messages (JSON)';

CREATE OR REPLACE TABLE RAW.KYC_NOTES (
  NOTE_ID VARCHAR PRIMARY KEY, CUSTOMER_ID VARCHAR, NOTE_DATE DATE,
  AUTHOR VARCHAR, NOTE_TEXT VARCHAR
) COMMENT = 'Unstructured onboarding / periodic KYC officer notes';

CREATE OR REPLACE TABLE RAW.ADVERSE_MEDIA (
  ARTICLE_ID VARCHAR PRIMARY KEY, PUBLISHED_DATE DATE, SOURCE VARCHAR,
  HEADLINE VARCHAR, BODY VARCHAR, MENTIONED_NAME VARCHAR, CITY VARCHAR
) COMMENT = 'Unstructured news feed (synthetic, fictional publications)';

CREATE OR REPLACE TABLE RAW.WATCHLIST (
  ENTRY_ID VARCHAR PRIMARY KEY, NAME VARCHAR, LIST_TYPE VARCHAR,
  COUNTRY VARCHAR, ADDED_DATE DATE, REMARKS VARCHAR
) COMMENT = 'Internal / consolidated watchlist (synthetic)';

CREATE OR REPLACE TABLE RAW.FRAUD_COMPLAINTS (
  COMPLAINT_ID VARCHAR PRIMARY KEY, REPORTED_TS TIMESTAMP_NTZ, CHANNEL VARCHAR,
  VICTIM_BANK VARCHAR, VICTIM_STATE VARCHAR, BENEFICIARY_ACCOUNT_ID VARCHAR,
  TXN_ID VARCHAR, AMOUNT NUMBER(14,2), COMPLAINT_TEXT VARCHAR
) COMMENT = 'Cyber-fraud complaints received against our beneficiary accounts (synthetic NCRP-style feed)';

CREATE OR REPLACE TABLE RAW.DOCS (
  DOC_ID VARCHAR, CHUNK_ID VARCHAR PRIMARY KEY, TITLE VARCHAR, DOC_TYPE VARCHAR,
  SECTION VARCHAR, CHUNK_TEXT VARCHAR, SOURCE_FILE VARCHAR, LOADED_AT TIMESTAMP_NTZ
) COMMENT = 'Chunked policy, SOP and typology documents for retrieval';

-- ============================ GOV ====================================
CREATE OR REPLACE TABLE GOV.GROUND_TRUTH (
  ACCOUNT_ID VARCHAR, IS_MULE BOOLEAN, RING_KEY VARCHAR, TYPOLOGY VARCHAR, ROLE VARCHAR
) COMMENT = 'Synthetic ground truth. NEVER read by detection code - evaluation only.';

CREATE OR REPLACE TABLE GOV.AGENT_AUDIT_LOG (
  EVENT_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), AGENT VARCHAR, ACTION VARCHAR,
  CASE_ID VARCHAR, MODEL VARCHAR, STATUS VARCHAR, DURATION_MS NUMBER,
  DETAILS VARIANT, INVOKED_BY VARCHAR
) COMMENT = 'Immutable trail of every automated / AI action';

CREATE OR REPLACE TABLE GOV.REGION_ACCESS (ROLE_NAME VARCHAR, REGION VARCHAR);
INSERT INTO GOV.REGION_ACCESS VALUES
  ('FINCRIME_ANALYST','South'), ('FINCRIME_ANALYST','West');

-- ========================== ANALYTICS ================================
CREATE OR REPLACE TABLE ANALYTICS.HISTORICAL_LABELS (
  ACCOUNT_ID VARCHAR, LABEL NUMBER(1), SOURCE VARCHAR, LABELED_AT TIMESTAMP_NTZ
) COMMENT = 'Outcomes of previously closed investigations (training labels)';

CREATE OR REPLACE TABLE ANALYTICS.RULE_CONFIG (
  RULE_ID VARCHAR PRIMARY KEY, RULE_NAME VARCHAR, FEATURE VARCHAR, OPERATOR VARCHAR,
  THRESHOLD FLOAT, MIN_TOTAL_IN_30D FLOAT, BASE_WEIGHT FLOAT, WEIGHT FLOAT,
  TYPOLOGY VARCHAR, DESCRIPTION VARCHAR, ENABLED BOOLEAN, UPDATED_AT TIMESTAMP_NTZ
);

INSERT INTO ANALYTICS.RULE_CONFIG
SELECT $1,$2,$3,$4,$5,$6,$7,$7,$8,$9,TRUE,CURRENT_TIMESTAMP() FROM VALUES
 ('R01','RAPID_PASS_THROUGH','SAME_DAY_PASS_THROUGH_RATIO','>=',0.70,50000,2.0,'MULE_LAYERING','Most credited money leaves the account the same day'),
 ('R02','HIGH_FAN_IN','DISTINCT_IN_CP_30D','>=',10,25000,1.0,'MULE_LAYERING','Many distinct remitters in 30 days'),
 ('R03','INCOME_MISMATCH','INCOME_MULTIPLE','>=',3,50000,1.5,'ANY','Annualised inflow >= 3x declared income'),
 ('R04','NEW_ACCOUNT_HIGH_VALUE','NEW_ACCT_HIGH_VALUE','>=',1,0,1.5,'MULE_LAYERING','Account < 90 days old receiving >= 2 lakh in 30 days'),
 ('R05','CASH_OUT_HEAVY','CASH_OUT_RATIO','>=',0.50,50000,1.5,'MULE_LAYERING','Majority of outflow withdrawn as cash'),
 ('R06','STRUCTURING','NEAR_THRESHOLD_CASH_CNT_30D','>=',3,0,2.0,'STRUCTURING','Repeated cash deposits just below the 50k PAN threshold'),
 ('R07','SHARED_DEVICE','SHARED_DEVICE_PEERS','>=',3,0,1.5,'MULE_LAYERING','Device used by 4+ different accounts'),
 ('R08','VICTIM_COMPLAINT','COMPLAINT_CNT','>=',1,0,2.5,'MULE_LAYERING','Named as beneficiary in a cyber-fraud complaint'),
 ('R09','VDA_OUTFLOW','VDA_OUT_30D','>=',50000,0,1.0,'MULE_LAYERING','Material outflow to crypto (VDA) exchanges'),
 ('R10','CIRCULAR_FLOW','IN_CIRCULAR_FLOW','>=',1,0,2.0,'ROUND_TRIPPING','Large funds return to origin via 2-3 hops'),
 ('R11','VAGUE_PURPOSE','VAGUE_PURPOSE_CNT_30D','>=',2,0,0.5,'ANY','High-value outward payments with vague remittance info'),
 ('R12','NIGHT_ACTIVITY','NIGHT_TXN_RATIO','>=',0.30,25000,0.5,'ANY','30%+ of transactions between 00:00 and 05:00');

CREATE OR REPLACE TABLE ANALYTICS.RULE_CONFIG_HISTORY (
  CHANGED_AT TIMESTAMP_NTZ, RULE_ID VARCHAR, OLD_WEIGHT FLOAT, NEW_WEIGHT FLOAT,
  PRECISION FLOAT, N_HITS NUMBER, REASON VARCHAR
);

CREATE OR REPLACE TABLE ANALYTICS.ACCOUNT_RISK (
  ACCOUNT_ID VARCHAR, CUSTOMER_ID VARCHAR, REGION VARCHAR, ACCOUNT_TYPE VARCHAR,
  OCCUPATION VARCHAR, ACCOUNT_AGE_DAYS NUMBER, TOTAL_IN_30D FLOAT, TOTAL_OUT_30D FLOAT,
  RULE_SCORE FLOAT, ML_SCORE FLOAT, GRAPH_SCORE FLOAT, FINAL_SCORE FLOAT,
  RISK_BAND VARCHAR, RULES_HIT VARCHAR, RULE_COUNT NUMBER, RING_ID VARCHAR,
  IS_ALERTED BOOLEAN, SCORED_AT TIMESTAMP_NTZ
) COMMENT = 'Latest blended risk score per account';

CREATE OR REPLACE TABLE ANALYTICS.RINGS (
  RING_ID VARCHAR, TYPOLOGY VARCHAR, MEMBER_COUNT NUMBER, COLLECTORS NUMBER, LAYERS NUMBER,
  CASH_OUT_NODES NUMBER, TOTAL_EXTERNAL_IN_30D FLOAT, INTERNAL_FLOW_30D FLOAT,
  CASH_OUT_30D FLOAT, VDA_OUT_30D FLOAT, COMPLAINT_CNT NUMBER, SHARED_DEVICES NUMBER,
  RING_SCORE FLOAT, PRIMARY_REGION VARCHAR, LAST_ACTIVITY_TS TIMESTAMP_NTZ, DETECTED_AT TIMESTAMP_NTZ
) COMMENT = 'Connected components of suspicious accounts (money + device graph)';

CREATE OR REPLACE TABLE ANALYTICS.RING_MEMBERS (
  RING_ID VARCHAR, ACCOUNT_ID VARCHAR, ROLE VARCHAR, PRELIM_SCORE FLOAT,
  IN_30D FLOAT, OUT_30D FLOAT, DETECTED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE ANALYTICS.RING_EDGES (
  RING_ID VARCHAR, SRC VARCHAR, DST VARCHAR, EDGE_TYPE VARCHAR, AMOUNT FLOAT, TXN_COUNT NUMBER
);

CREATE OR REPLACE TABLE ANALYTICS.CASES (
  CASE_ID VARCHAR PRIMARY KEY, CASE_TYPE VARCHAR, RING_ID VARCHAR, PRIMARY_ACCOUNT_ID VARCHAR,
  REGION VARCHAR, TYPOLOGY VARCHAR, STATUS VARCHAR, PRIORITY VARCHAR, PRIORITY_SCORE FLOAT,
  AMOUNT_AT_RISK FLOAT, MEMBER_COUNT NUMBER, ASSIGNED_TO VARCHAR, TRIAGE_RATIONALE VARCHAR,
  INVESTIGATION_SUMMARY VARIANT, CONFIDENCE FLOAT,
  CREATED_AT TIMESTAMP_NTZ, UPDATED_AT TIMESTAMP_NTZ, SLA_DUE_AT TIMESTAMP_NTZ,
  CLOSED_AT TIMESTAMP_NTZ, DISPOSITION VARCHAR
) COMMENT = 'Investigation cases. Status: NEW > TRIAGED > INVESTIGATED > PENDING_REVIEW > CLOSED_*';

CREATE OR REPLACE TABLE ANALYTICS.CASE_EVIDENCE (
  CASE_ID VARCHAR, EVIDENCE_TYPE VARCHAR, TITLE VARCHAR, PAYLOAD VARIANT,
  CREATED_BY VARCHAR, CREATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE ANALYTICS.STR_DRAFTS (
  CASE_ID VARCHAR, VERSION NUMBER, STATUS VARCHAR, DRAFT VARIANT, NARRATIVE VARCHAR,
  CITATIONS VARIANT, CITATION_VALIDITY FLOAT, FAITHFULNESS_SCORE FLOAT, JUDGE_NOTES VARCHAR,
  MODEL VARCHAR, CREATED_AT TIMESTAMP_NTZ, REVIEWED_BY VARCHAR, REVIEWED_AT TIMESTAMP_NTZ
) COMMENT = 'AI-drafted Suspicious Transaction Reports awaiting human approval';

CREATE OR REPLACE TABLE ANALYTICS.CASE_FEEDBACK (
  CASE_ID VARCHAR, DISPOSITION VARCHAR, REVIEWER VARCHAR, NOTES VARCHAR, CREATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE ANALYTICS.FEEDBACK_LABELS (
  ACCOUNT_ID VARCHAR, LABEL NUMBER(1), CASE_ID VARCHAR, CREATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE ANALYTICS.EVAL_RESULTS (
  RUN_TS TIMESTAMP_NTZ, DETECTOR VARCHAR, PRECISION FLOAT, RECALL FLOAT, F1 FLOAT,
  TP NUMBER, FP NUMBER, FN NUMBER, ALERTED NUMBER, NOTES VARCHAR
) COMMENT = 'Detection quality vs held-out synthetic ground truth';

CREATE OR REPLACE TABLE ANALYTICS.MODEL_LOG (
  TRAINED_AT TIMESTAMP_NTZ, MODEL_NAME VARCHAR, VERSION VARCHAR, AUC_HOLDOUT FLOAT,
  N_TRAIN NUMBER, N_POS NUMBER, FEATURES VARCHAR, REGISTRY_STATUS VARCHAR, STAGE_PATH VARCHAR
);

-- ============================== AI ===================================
CREATE OR REPLACE TABLE AI.KYC_EXTRACT (
  CUSTOMER_ID VARCHAR, NOTE_ID VARCHAR, EXTRACTED VARIANT, MODEL VARCHAR, EXTRACTED_AT TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE AI.MEDIA_LABELS (
  ARTICLE_ID VARCHAR, RISK_LABEL VARCHAR, LABELED_AT TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE AI.MEDIA_MATCHES (
  CUSTOMER_ID VARCHAR, ARTICLE_ID VARCHAR, NAME_SIMILARITY NUMBER, AI_CONFIRMED BOOLEAN,
  RISK_LABEL VARCHAR, HEADLINE VARCHAR, MATCHED_AT TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE AI.WATCHLIST_HITS (
  CUSTOMER_ID VARCHAR, ENTRY_ID VARCHAR, WATCHLIST_NAME VARCHAR, LIST_TYPE VARCHAR,
  NAME_SIMILARITY NUMBER, MATCHED_AT TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE AI.COMPLAINT_LABELS (
  COMPLAINT_ID VARCHAR, SCAM_TYPE VARCHAR, LABELED_AT TIMESTAMP_NTZ
);
