-- =====================================================================
-- MuleWatch :: 99_suspend_all.sql  - stop all background spend after the demo
-- =====================================================================
USE ROLE MULEWATCH_ADMIN;
USE DATABASE MULEWATCH;

ALTER TASK IF EXISTS APP.MW_STREAM_SIM SUSPEND;
ALTER TASK IF EXISTS APP.MW_ROOT_SCORE SUSPEND;
ALTER TASK IF EXISTS APP.MW_LEARN SUSPEND;

ALTER DYNAMIC TABLE IF EXISTS CURATED.ACCOUNT_FEATURES SUSPEND;
ALTER DYNAMIC TABLE IF EXISTS CURATED.DAILY_CHANNEL_STATS SUSPEND;
ALTER DYNAMIC TABLE IF EXISTS CURATED.CIRCULAR_FLOWS SUSPEND;
ALTER DYNAMIC TABLE IF EXISTS CURATED.DEVICE_SHARING SUSPEND;
ALTER DYNAMIC TABLE IF EXISTS CURATED.DEVICE_EVENTS_FLAT SUSPEND;
ALTER DYNAMIC TABLE IF EXISTS CURATED.PAYMENT_MSG_FLAT SUSPEND;
ALTER DYNAMIC TABLE IF EXISTS CURATED.TXN_ENRICHED SUSPEND;

ALTER CORTEX SEARCH SERVICE IF EXISTS AI.POLICY_SEARCH SUSPEND INDEXING;
ALTER CORTEX SEARCH SERVICE IF EXISTS AI.MEDIA_SEARCH SUSPEND INDEXING;
ALTER CORTEX SEARCH SERVICE IF EXISTS AI.COMPLAINT_SEARCH SUSPEND INDEXING;

ALTER WAREHOUSE MULEWATCH_WH SUSPEND;

-- To resume later: ALTER DYNAMIC TABLE ... RESUME; ALTER CORTEX SEARCH SERVICE ... RESUME INDEXING;
-- and SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('MULEWATCH.APP.MW_ROOT_SCORE');
